version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: 
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test
workflows:
  build_test:
    jobs:
      - run_tests
