version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.15.0

jobs:
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
