version: 2.1
jobs:
  run_tests:
    docker:
     - image: circleci/node:20
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
            npm install
      - run:
          name: Run run_tests
          command:
            npm run test
      - store_test_results:
          path: test_results
workflows:
  build_test:
    jobs:
      - run_tests